#!/usr/bin/env python3
"""Build the 10 head-to-head comparisons for the 2026 top-5 3D printers.
Specs verified in two rounds (Oct 2026): 3dprinting.com, Tom's Hardware,
How-To Geek, makers101.com, VoxelMatters, Prusa official, Bambu official.
Run: python3 scripts/build_3dprinter_comparisons.py  (then regenerate site)
"""
import json
from pathlib import Path

BASE = Path(__file__).parent.parent

PRODUCTS = {
"P2S": {
  "name": "Bambu Lab P2S Combo",
  "price_range": "$749",
  "best_for": "Most users — the safe 2026 pick",
  "summary": "The 2026 mainstream king: enclosed CoreXY, 600mm/s, AMS 2 Pro multi-color with filament drying, 5-inch touchscreen and AI failure detection. The easiest path to great prints.",
  "specs": {
    "Build Volume": "256 × 256 × 256 mm",
    "Speed": "600mm/s, 20,000 mm/s² acceleration",
    "Nozzle Temp": "300°C, hardened steel",
    "Multi-color": "AMS 2 Pro — 4 colors per unit, up to 16",
    "Chamber": "Enclosed, ~50°C passive",
    "Bed Leveling": "Fully automatic",
    "Firmware": "Bambu OS (closed)",
    "Slicer": "Bambu Studio",
  },
},
"X2D": {
  "name": "Bambu Lab X2D Combo",
  "price_range": "$899",
  "best_for": "Engineering + multi-material without the waste",
  "summary": "Tom's Hardware's 2026 best overall: dual nozzles (direct-drive main + Bowden support nozzle), 65°C active heated chamber, 70–80% less purge waste than AMS-only. The thinking maker's Bambu.",
  "specs": {
    "Build Volume": "256 × 256 × 260 mm",
    "Speed": "1,000mm/s, 20,000 mm/s² acceleration",
    "Nozzle Temp": "300°C, hardened steel",
    "Multi-color": "Dual nozzle + AMS 2 Pro — up to 25 colors",
    "Chamber": "65°C active heated",
    "Bed Leveling": "Fully automatic",
    "Firmware": "Bambu OS (closed)",
    "Slicer": "Bambu Studio",
  },
},
"CENTAURI": {
  "name": "Elegoo Centauri Carbon",
  "price_range": "$299",
  "best_for": "Budget engineering prints — carbon fiber on a budget",
  "summary": "The 2026 budget disruptor: enclosed CoreXY, 500mm/s, 320°C nozzle that handles carbon-fiber filaments — at one-third the price of a P2S. No multicolor on v1, smaller community, unbeatable value for functional prints.",
  "specs": {
    "Build Volume": "256 × 256 × 256 mm",
    "Speed": "500mm/s, 20,000 mm/s² acceleration",
    "Nozzle Temp": "320°C, hardened steel",
    "Multi-color": "No (v1); CC2 Combo adds 4-color at $449",
    "Chamber": "Enclosed, passive",
    "Bed Leveling": "121-point automatic",
    "Firmware": "Klipper-based (Elegoo fork)",
    "Slicer": "Elegoo Slicer / OrcaSlicer / Cura",
  },
},
"COREONE": {
  "name": "Prusa CORE One+",
  "price_range": "$949–$1,299",
  "best_for": "Reliability-first buyers, open-source, repairable for a decade",
  "summary": "Prusa's CoreXY flagship: 55°C active chamber, 300°C nozzle (400°C with HT upgrade), fully open-source and user-repairable, no cloud account required. The buy-it-for-a-decade printer.",
  "specs": {
    "Build Volume": "250 × 220 × 270 mm",
    "Speed": "500mm/s class, Input Shaper",
    "Nozzle Temp": "300°C (400°C with HT upgrade)",
    "Multi-color": "MMU3 add-on (5 filaments)",
    "Chamber": "55°C active heated",
    "Bed Leveling": "Load-cell, fully automatic",
    "Firmware": "Open-source Prusa firmware",
    "Slicer": "PrusaSlicer",
  },
},
"U1": {
  "name": "Snapmaker U1",
  "price_range": "$899",
  "best_for": "Multi-color printing without the purge waste",
  "summary": "The consumer toolchanger: 4 independent direct-drive toolheads swap in ~5 seconds with near-zero purge waste. Brilliant for multi-color work; open frame needs the $149 Top Cover for ABS/ASA/PA.",
  "specs": {
    "Build Volume": "270 × 270 × 270 mm",
    "Speed": "500mm/s, 20,000 mm/s² acceleration",
    "Nozzle Temp": "300°C",
    "Multi-color": "4 toolheads — 4 colors max, no expansion",
    "Chamber": "Open frame (+$149 Top Cover for enclosure)",
    "Bed Leveling": "Fully automatic",
    "Firmware": "Klipper-based, open source",
    "Slicer": "Snapmaker Orca (beta)",
  },
},
}

def D(name, a, b, winner, why):
    return {"name": name, "a": a, "b": b, "winner": winner, "why": why}

# (key_a, key_b, slug, winner_side, key_differences, dimensions, verdict)
PAIRS = [
("P2S", "X2D", "bambu-p2s-vs-x2d", "b",
 [
  "Price: P2S Combo $749 vs X2D Combo $899 — $100 buys dual nozzles + heated chamber",
  "Nozzles: P2S single direct-drive vs X2D dual (direct main + Bowden support nozzle)",
  "Chamber: P2S ~50°C passive vs X2D 65°C active heated",
  "Speed: P2S 600mm/s vs X2D 1,000mm/s (main nozzle)",
  "Multi-color waste: X2D's dual nozzle cuts purge waste 70–80% vs AMS-only P2S",
 ],
 [
  D("🧪 Materials", "PLA, PETG, ABS, ASA ideal; 300°C hotend, ~50°C passive chamber.",
    "Same filaments plus cleaner Nylon/PC results; 65°C active chamber, 300°C hotend.",
    "b", "The X2D's active 65°C chamber is the difference between hoping nylon sticks and knowing it will."),
  D("🎨 Multi-color", "AMS 2 Pro: up to 16 colors, but every swap purges filament.",
    "Dual nozzle + AMS 2 Pro: support nozzle eliminates most purging, up to 25 colors.",
    "b", "If you print multi-color regularly, the X2D's purge savings pay for the $100 gap fast."),
  D("🔧 Ease of Use", "The simplest enclosed Bambu: 15-minute setup, 5\" touchscreen, AI monitoring.",
    "Same Bambu ease plus more sensors; dual-nozzle adds slight complexity.",
    "a", "For pure plug-and-print simplicity on PLA/PETG, the P2S is still the easier machine."),
  D("👥 Community & Ecosystem", "MakerWorld (1M+ models), huge P2S user base, endless profiles.",
    "Same MakerWorld ecosystem; newer machine, smaller owner base so far.",
    "a", "The P2S inherits years of community profiles and troubleshooting threads."),
  D("💰 Value", "$749 all-in with AMS 2 Pro drying. Nothing simpler at this price.",
    "$899 — $100 more for dual nozzles, heated chamber, faster speeds.",
    "b", "Reviewers agree: the X2D's $100 premium buys far more than $100 of capability."),
 ],
 "The X2D is the better printer for $100 more — unless you print PLA and PETG exclusively, in which case the P2S gives identical results for less. Most buyers should stretch to the X2D."),

("P2S", "CENTAURI", "bambu-p2s-vs-centauri-carbon", "a",
 [
  "Price: P2S Combo $749 vs Centauri Carbon $299 — less than half",
  "Nozzle: Centauri 320°C beats P2S 300°C for high-temp engineering filaments",
  "Multi-color: P2S AMS 2 Pro (16 colors) vs Centauri v1 single-color only",
  "Ecosystem: Bambu MakerWorld + huge community vs smaller but growing Elegoo scene",
  "Software: Bambu Studio polish vs Klipper-based Elegoo (tinker-friendly, less refined)",
 ],
 [
  D("🧪 Materials", "PLA, PETG, ABS, ASA ideal; 300°C hardened hotend.",
    "PLA, PETG, ABS, ASA, TPU + carbon/glass-fiber reinforced; 320°C nozzle — hotter than P2S.",
    "b", "Centauri's 320°C nozzle opens more engineering filaments at one-third the price."),
  D("🎨 Multi-color", "AMS 2 Pro with filament drying — up to 16 colors, dead simple.",
    "No multi-color on v1. Single filament, single color.",
    "a", "If multi-color matters at all, the P2S wins by default — Centauri can't play."),
  D("👥 Community & Ecosystem", "MakerWorld's million-plus models, profiles for everything, big support network.",
    "Growing Elegoo community, OrcaSlicer profiles maturing, but years behind Bambu.",
    "a", "When something goes wrong at 11pm, the P2S community has already solved it."),
  D("🔧 Ease of Use", "15-minute setup, auto everything, AI failure detection, great app.",
    "Good out-of-box experience, but expects more user involvement when tuning.",
    "a", "The P2S is the 'it just works' printer; Centauri rewards tinkerers."),
  D("💰 Value", "$749 for the complete multi-color package.",
    "$299 — nothing else enclosed and this fast exists at this price.",
    "b", "On pure price-to-hardware ratio, nothing touches the Centauri Carbon."),
 ],
 "Buy the P2S if you want multi-color, the best software, and zero-fuss printing. Buy the Centauri Carbon if you print functional single-color parts and want 80% of the capability for 37% of the money."),

("P2S", "COREONE", "bambu-p2s-vs-prusa-core-one-plus", "a",
 [
  "Price: P2S Combo $749 vs CORE One+ $949–$1,299 assembled",
  "Philosophy: Bambu closed ecosystem vs Prusa fully open-source and repairable",
  "Multi-color: P2S AMS 2 Pro (16 colors) vs CORE One+ MMU3 add-on (5 filaments)",
  "Cloud: P2S leans on Bambu cloud vs CORE One+ works fully offline, no account needed",
  "Chamber: P2S ~50°C passive vs CORE One+ 55°C active",
 ],
 [
  D("🧪 Materials", "PLA–ASA sweet spot; 300°C hotend, passive chamber.",
    "Same range plus 400°C HT upgrade path for PPS-class polymers; 55°C active chamber.",
    "b", "The CORE One+'s 400°C upgrade path is in another league for exotic filaments."),
  D("🎨 Multi-color", "AMS 2 Pro: polished, drying, up to 16 colors.",
    "MMU3 add-on: 5 filaments, more hands-on, less polished.",
    "a", "For multi-color, Bambu's AMS system is years ahead in refinement."),
  D("🔧 Repairability", "Proprietary parts, limited self-service; great warranty instead.",
    "Every part user-replaceable, open-source, spare parts stocked for years.",
    "b", "In year six, the Prusa owner orders a $20 part; the Bambu owner hopes support still stocks it."),
  D("🔒 Privacy & Control", "Cloud-connected by design; LAN mode exists but limited.",
    "Fully offline capable, no account, no telemetry. Your printer, your data.",
    "b", "If cloud dependence bothers you, this alone decides it."),
  D("💰 Value", "$749 complete with multi-color and drying.",
    "$949+ before multi-color; you're paying for longevity and openness.",
    "a", "Dollar for dollar today, the P2S gives you more printer."),
 ],
 "For most buyers in 2026, the P2S wins on capability-per-dollar and ease. Choose the CORE One+ if open-source, repairability, and a decade of spare parts matter more to you than multi-color polish."),

("P2S", "U1", "bambu-p2s-vs-snapmaker-u1", "a",
 [
  "Price: P2S Combo $749 vs U1 $899 (+$149 Top Cover for engineering filaments)",
  "Multi-color: P2S AMS purge-based (16 colors) vs U1 4 toolheads, near-zero waste",
  "Enclosure: P2S fully enclosed vs U1 open frame (Top Cover ships Nov 2026)",
  "Ecosystem: MakerWorld + Bambu Studio vs Snapmaker Orca (beta) + smaller library",
  "Build volume: P2S 256³ vs U1 270³ mm",
 ],
 [
  D("🎨 Multi-color", "AMS 2 Pro: up to 16 colors, but purge tower waste on every swap.",
    "4 toolheads swap in ~5 seconds with ~4g waste — 5× less than purge systems.",
    "b", "The U1's toolchanger is genuinely the future of multi-color: fast, clean, nearly wasteless."),
  D("🧪 Materials", "Enclosed with ~50°C chamber: ABS/ASA ready today.",
    "Open frame today — PLA/PETG/TPU only until the $149 Top Cover arrives.",
    "a", "Right now, the P2S prints engineering filaments and the U1 mostly can't."),
  D("🔧 Ease of Use", "Mature software, AI monitoring, huge profile library.",
    "Beta slicer, smaller community, 45-minute assembly with 4 filament paths.",
    "a", "The P2S is a finished product; the U1 is an exciting work in progress."),
  D("👥 Community & Ecosystem", "MakerWorld's million models and endless Bambu profiles.",
    "Growing fast post-Kickstarter ($20.6M raised), but years behind.",
    "a", "Ecosystem maturity isn't close — yet."),
  D("💰 Value", "$749 all-in, everything included.",
    "$899 + $149 Top Cover = $1,048 for full capability.",
    "a", "True all-in cost favors the P2S by $250."),
 ],
 "The U1's toolchanger is brilliant, but today the P2S is the more complete printer for less money. Revisit the U1 once the Top Cover ships and Snapmaker Orca matures — multi-color's future is toolchanging."),

("X2D", "CENTAURI", "bambu-x2d-vs-centauri-carbon", "a",
 [
  "Price: X2D Combo $899 vs Centauri Carbon $299 — 3× the price",
  "Chamber: X2D 65°C active vs Centauri passive enclosure",
  "Multi-color: X2D dual nozzle + AMS (25 colors) vs Centauri single-color",
  "Nozzle: Centauri 320°C actually beats X2D's 300°C",
  "Speed: X2D 1,000mm/s vs Centauri 500mm/s",
 ],
 [
  D("🧪 Materials", "65°C active chamber + 300°C: Nylon/PC with confidence.",
    "320°C nozzle beats the X2D on paper; passive chamber limits real-world Nylon.",
    "b", "Spec-sheet vs reality: the Centauri's hotter nozzle is real, but chamber heating matters more."),
  D("🎨 Multi-color", "Dual nozzles + AMS: 25 colors, minimal waste.",
    "None on v1.",
    "a", "Not a contest — the X2D plays a sport the Centauri doesn't."),
  D("🔧 Ease of Use", "Bambu's polished setup, AI monitoring, great app.",
    "Solid for the price, more hands-on.",
    "a", "The X2D holds your hand; the Centauri expects you to read the manual."),
  D("👥 Community & Ecosystem", "MakerWorld + massive Bambu base.",
    "Smaller, growing Elegoo scene.",
    "a", "Same story as every Bambu-vs-Elegoo matchup."),
  D("💰 Value", "$899 of serious engineering capability.",
    "$299 — the value king of 2026, full stop.",
    "b", "Three X2D's worth of Centauris is a print farm. Value is not close."),
 ],
 "The X2D is three times the printer and three times the price. If your budget stretches, the heated chamber and multi-color are transformative. If it doesn't, the Centauri Carbon remains 2026's most absurd value."),

("X2D", "COREONE", "bambu-x2d-vs-prusa-core-one-plus", "a",
 [
  "Price: X2D Combo $899 vs CORE One+ $949–$1,299",
  "Multi-material: X2D dual nozzle + AMS vs CORE One+ MMU3",
  "Chamber: X2D 65°C active vs CORE One+ 55°C active",
  "Philosophy: Bambu closed/polished vs Prusa open/repairable",
  "Nozzle: both 300°C (Prusa 400°C with HT upgrade)",
 ],
 [
  D("🧪 Materials", "65°C chamber, 300°C — excellent for Nylon/PC.",
    "55°C chamber, 300°C stock, 400°C HT upgrade path for exotics.",
    "b", "The HT upgrade gives Prusa the ceiling for truly exotic polymers."),
  D("🎨 Multi-color", "Dual nozzle kills purge waste; AMS scales to 25 colors.",
    "MMU3: 5 filaments, purge-based, more fiddly.",
    "a", "Multi-material isn't close — the X2D is a generation ahead."),
  D("🔧 Repairability", "Proprietary; great while supported.",
    "Fully open, parts for years, fix it yourself at midnight.",
    "b", "The Prusa is the last printer you'll need to buy; the X2D is the best printer to buy now."),
  D("🔒 Privacy & Control", "Cloud-first design.",
    "Offline-first, no account needed.",
    "b", "Decisive if you care about data sovereignty."),
  D("💰 Value", "$899 complete with dual-nozzle multi-material.",
    "$949+ and multi-color costs extra.",
    "a", "More capability per dollar today."),
 ],
 "The X2D wins for most buyers: cheaper, better multi-material, hotter chamber. The CORE One+ wins for the buyer who values openness, repairability, and a 400°C upgrade path over multi-color polish."),

("X2D", "U1", "bambu-x2d-vs-snapmaker-u1", "a",
 [
  "Price: X2D Combo $899 all-in vs U1 $899 + $149 Top Cover",
  "Multi-color: X2D dual nozzle (25 colors) vs U1 4 toolheads (4 colors, less waste)",
  "Chamber: X2D 65°C active built-in vs U1 passive 50°C with Top Cover (Nov 2026)",
  "Filtration: X2D 3-stage HEPA built-in vs U1 Top Cover only",
  "Colors: X2D scales to 25 vs U1 hard-capped at 4",
 ],
 [
  D("🎨 Multi-color", "Dual nozzle + AMS: 25 colors, ~8g waste per print.",
    "4 toolheads: 4 colors max, ~4g waste — half the X2D's.",
    "b", "Per-swap, the U1 wastes less. But it's capped at 4 colors forever."),
  D("🧪 Materials", "65°C active chamber today: Nylon/PC with confidence.",
    "Needs Top Cover for ABS/ASA; 50°C passive max.",
    "a", "A 15°C chamber gap is the difference between reliable nylon and warping."),
  D("🔧 Ease of Use", "Mature Bambu Studio, AI monitoring, huge profiles.",
    "Beta Orca, newer ecosystem, more DIY spirit.",
    "a", "The X2D is polished; the U1 is promising."),
  D("💰 True Cost", "$899 — everything included, today.",
    "$1,048 with Top Cover, and filtration waits until November.",
    "a", "The U1's sticker price is misleading; the X2D's isn't."),
  D("🔮 Future-proof", "Closed system, but Bambu's track record is strong.",
    "Open Klipper, toolchanger architecture — more hackable long-term.",
    "b", "Tinkerers will get more years of fun from the U1's open platform."),
 ],
 "Today, the X2D is the more complete machine for less real money. The U1 is the more interesting machine — if you print multi-color constantly and can wait for the Top Cover, its toolchanger is the future."),

("CENTAURI", "COREONE", "elegoo-centauri-carbon-vs-prusa-core-one-plus", "b",
 [
  "Price: Centauri $299 vs CORE One+ $949–$1,299 — 3–4× the price",
  "Nozzle: Centauri 320°C beats CORE One+ 300°C stock (400°C with HT upgrade)",
  "Philosophy: budget closed-box vs premium open-source",
  "Multi-color: neither is great (Centauri none, Prusa MMU3 add-on)",
  "Community: Elegoo growing vs Prusa legendary support + Printables",
 ],
 [
  D("🧪 Materials", "320°C nozzle, passive chamber — great for the price.",
    "55°C active chamber, 400°C HT path — a different league with the upgrade.",
    "b", "Stock vs stock it's closer than the price suggests; with the HT upgrade it's over."),
  D("🔧 Repairability", "Budget construction, limited parts network.",
    "The gold standard: open-source, parts for a decade.",
    "b", "This is what the $900 premium mostly buys: the next ten years."),
  D("👥 Community & Ecosystem", "Growing fast, OrcaSlicer-based.",
    "Printables, legendary support, MMU3 ecosystem.",
    "b", "Prusa's community is the industry's benchmark."),
  D("🔧 Ease of Use", "Surprisingly polished for $299.",
    "Refined but expects you to learn your machine.",
    "a", "The Centauri asks less of you on day one."),
  D("💰 Value", "$299 — four printers for the price of one Prusa.",
    "$949+ — you're buying longevity, not specs.",
    "a", "Nothing in 2026 beats the Centauri on value. Nothing."),
 ],
 "The honest answer: the Centauri Carbon gives you 80% of the printing for 25% of the money. The CORE One+ earns its premium in year three, when it's still printing perfectly and every part is still available. Buy the Prusa if you can afford to think in decades."),

("CENTAURI", "U1", "elegoo-centauri-carbon-vs-snapmaker-u1", "b",
 [
  "Price: Centauri $299 vs U1 $899 — 3× the price",
  "Multi-color: Centauri none vs U1 4 toolheads",
  "Enclosure: Centauri enclosed vs U1 open frame",
  "Build volume: Centauri 256³ vs U1 270³ mm",
  "Nozzle: Centauri 320°C vs U1 300°C",
 ],
 [
  D("🎨 Multi-color", "Single color, full stop.",
    "4 toolheads, 5-second swaps, near-zero waste.",
    "b", "If you want multi-color under $1,000, the U1 is the only real answer."),
  D("🧪 Materials", "Enclosed + 320°C: ABS/ASA/carbon-fiber today.",
    "Open frame: PLA/PETG/TPU until the Top Cover.",
    "a", "Today, the $299 printer handles tougher filaments than the $899 one."),
  D("🔧 Simplicity", "One nozzle, one filament path, fewer things to break.",
    "Four toolheads, four filament paths, beta slicer.",
    "a", "The Centauri is the simpler, more reliable machine right now."),
  D("📦 Build Volume", "256³ mm — standard.",
    "270³ mm — noticeably roomier for batch prints.",
    "b", "The U1's extra 14mm per axis adds up on big projects."),
  D("💰 Value", "$299 all-in.",
    "$899 (+$149 Top Cover for full capability).",
    "a", "The value gap is enormous and the Centauri wins it walking."),
 ],
 "Different tools: the Centauri is the unbeatable budget workhorse for functional single-color prints; the U1 is the multi-color specialist. If you don't need multi-color, save $600 and buy the Centauri."),

("COREONE", "U1", "prusa-core-one-plus-vs-snapmaker-u1", "a",
 [
  "Price: CORE One+ $949–$1,299 vs U1 $899 (+$149 Top Cover)",
  "Multi-color: CORE One+ MMU3 (5 filaments) vs U1 4 toolheads (less waste)",
  "Enclosure: CORE One+ enclosed 55°C vs U1 open frame",
  "Philosophy: both open-source friendly; Prusa mature, Snapmaker newer",
  "Reliability: Prusa legendary vs U1 first-gen toolchanger",
 ],
 [
  D("🎨 Multi-color", "MMU3: 5 filaments, purge-based, proven but wasteful.",
    "4 toolheads: near-zero waste, 5-second swaps.",
    "b", "The U1's toolchanger embarrasses every purge-based system, MMU3 included."),
  D("🧪 Materials", "Enclosed, 55°C active, 400°C HT path.",
    "Open frame until Top Cover; 300°C max.",
    "a", "For engineering filaments, the Prusa is ready today and goes hotter."),
  D("🔧 Reliability", "Prusa's legendary consistency, parts for years.",
    "First-gen toolchanger; long-term durability unproven.",
    "a", "The CORE One+ is the safe pair of hands."),
  D("👥 Community & Ecosystem", "Printables, decades of trust.",
    "Post-Kickstarter energy, growing fast.",
    "a", "Prusa's ecosystem is the industry benchmark."),
  D("💰 Value", "$949+ for the complete reliable package.",
    "$899 of multi-color brilliance, $1,048 for full capability.",
    "b", "If multi-color is the job, the U1 does it better for less."),
 ],
 "The reliability-first buyer takes the CORE One+ without hesitation. The multi-color-obsessed buyer takes the U1 and accepts first-gen quirks. There's no wrong answer — only different priorities."),
]

def build():
    path = BASE / "data" / "comparisons.json"
    data = json.loads(path.read_text())
    existing_slugs = {c["slug"] for c in data["comparisons"]}
    added = 0
    for ka, kb, slug, winner, kds, dims, verdict in PAIRS:
        if slug in existing_slugs:
            print("skip (exists):", slug)
            continue
        pa, pb = PRODUCTS[ka], PRODUCTS[kb]
        data["comparisons"].append({
            "slug": slug,
            "title": f'{pa["name"]} vs {pb["name"]}',
            "category": "3D Printer",
            "source_guide": "best-3d-printer-2026",
            "product_a": pa["name"],
            "product_b": pb["name"],
            "winner": winner,
            "inline_products": {pa["name"]: pa, pb["name"]: pb},
            "key_differences": kds,
            "dimensions": dims,
            "verdict": verdict,
        })
        added += 1
        print("added:", slug)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2))
    print(f"done, {added} new comparisons")

if __name__ == "__main__":
    build()
